apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: slack
  namespace: flux-system
spec:
  summary: "FluxV2 is having an issue on [YOUR_CLUSTER_NAME] cluster"
  providerRef:
    name: your-slack-channel
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'