apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: your-slack-channel
  namespace: flux-system
spec:
  type: slack
  channel: the-name-of-the-workspace-channel-you-want-to-use
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: your-slack-app-token
