apiVersion: v1
kind: Secret
metadata:
  name: your-git-user
  namespace: flux-system
type: Opaque
data:
  #base64 the private SSH key of the Git user of your repo you will use to pull from it, its public key also needs to be setup on the other side (mostly its profile settings)
  identity: LS0tLS1CRUd...
  #github.com usage example : base64 below the correct line (github.com ecdsa-sha2-nistp256...) of this command output: ssh-keyscan github.com
  #gitlab.com usage example : base64 below the correct line (gitlab.com ecdsa-sha2-nistp256...) of this command output: ssh-keyscan gitlab.com
  known_hosts: Z2l0bGFiLmNv...
---