apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: your-namespace
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./path/to/your/manifests/folder
  prune: false
  sourceRef:
    kind: GitRepository
    name: your-repo
